### ISSUE TITLE
Added translations to the theme, for buttons, Sections, Search, and other stuff.

### ISSUE THREAD

**Issue by craftsmandigital** [craftsmandigital/capsule#1]
It is now possible to have a full Norwegian and English look. you can also easy translating the theme to other languages.
- Added a new  dir  i18n
- two new files for translation
  - i18n/en.yaml
  - i18n/no.yaml
- Added translation in the templates of capsule

**Comment by hackingjack** [comment]
The commit for the issue is 8b3acb86eb3486a89e7ddd130c1d08b64761ba88
the branch [i18n](../tree/i18n)

**Comment by craftsmandigital** [comment]
The commit for the issue is 8b3acb86eb3486a89e7ddd130c1d08b64761ba88
the branch [i18n](../tree/i18n)
